### ISSUE TITLE
ESC Setup / programming (bidirectional telemetry)

### ISSUE THREAD

**Issue by bob01** [rotorflight/rotorflight-firmware#101]
Provide ESC setup / programming functionality using the Tx via bidirectional telemetry on par with other modern R/C systems.

As heli pilots we are accustomed to being able to setup (set BEC voltage, change rotation, set cutoff behavior etc.) and tweak at the field (ESC internal gov gains etc). A growing number of ESCs support this functionality.
Support in RF.

**Comment by rotorflight** [comment]
Feel free to open PRs into master.
Release is on the RF- branch already.

**Comment by bob01** [comment]
Will do.

**Comment by rotorflight** [comment]
Work done for now.
