### ISSUE TITLE
Add RF specific tuning values to CMS

### ISSUE THREAD

**Issue by rotorflight** [rotorflight/rotorflight-firmware#103]
Let's compose a list here.

**Comment by rotorflight** [comment]
P I  D F O B gains

**Comment by rotorflight** [comment]
Governor parameters:
- Full headspeed
- PID master gain
- P I D F gains

**Comment by rotorflight** [comment]
Rescue parameters:
- pull-up collective
- climb collective
- hover collective

Additional:
- pull-up time
- climb time
- leveling gain
-

**Comment by rotorflight** [comment]
Additional tuning parameters (if space in CMS permits):
- Cyclic cross-coupling gain
- I-term relax cutoffs
- PID controller bandwidths (nine of them)

**Comment by AndersHoglund** [comment]
> Most important for tuning:
>     * P I  D F O B gains
>     * Yaw stop gains CW / CCW
>     * Yaw Collective (and cyclic) feedforward
>     * Yaw TTA gain

Done, #104 1.st commit.

**Comment by AndersHoglund** [comment]
> Governor parameters:
>     * Full headspeed
>     * PID master gain
>     * P I D F gains

Done, #104 second commit

**Comment by AndersHoglund** [comment]
Rescue parameters added in #107:
* pull-up collective
* pull-up time
* climb collective
* climb time
* hover collective
* leveling gain
* flip gain

**Comment by AndersHoglund** [comment]
All remaining items added  #107

**Comment by rotorflight** [comment]
All done for now!
