### ISSUE TITLE
iFlight_F411_PRO no Blackbox

### ISSUE THREAD

**Issue by jasc76** [rotorflight/rotorflight-firmware#13]
**Describe the bug**
Blackbox is not found with this FC. 

**To Reproduce**
Flash 4.2.12 20220401; Apply Defaults; BB not found
Flash Betaflight 4.3RC5 - BB chip found

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/42022027/163599253-4f267c64-01da-4002-a698-dcc09c94d26c.png)

**Comment by rotorflight** [comment]
Evidently the BB chip in question is not supported by BF 4.2, thus not supported by RF 4.2 either.
Will consider to add it later, either to 4.3 based RF, or as an addition to 4.2.

**Comment by jasc76** [comment]
I was just diggin through some BF stuff and saw this:
https://github.com/betaflight/betaflight/pull/11537
Maybe it just needs to be activated in the board definition

**Comment by jasc76** [comment]
winbond, is that the correct chip
![vlcsnap-2022-05-05-07h55m19s585](https://user-images.githubusercontent.com/42022027/166869601-ba24474a-5bc4-4bc0-b346-4553fedf11b4.png)
?

**Comment by jasc76** [comment]
I think its [W25Q64JVXGIM]

**Comment by jasc76** [comment]
test build installed and short bench test. Logging, download, opening in BB works

**Comment by rotorflight** [comment]
Fix will appear in 4.2.12-RC2
