### ISSUE TITLE
Bessel filter note

### ISSUE THREAD

**Issue by rtlopez** [rotorflight/rotorflight-firmware#16]
Hi,
I'm looking at the code and have a tiny doubt. 
In the filter.c https://github.com/rotorflight/rotorflight-firmware/blob/master/src/main/common/filter.c#L109 there is a fragment
```c
void biquadFilterInitBessel(biquadFilter_t *filter, float filterFreq, uint32_t refreshRate)
{
    biquadFilterInit(filter, filterFreq, refreshRate, 0, FILTER_BESSEL);
}
```
then later in https://github.com/rotorflight/rotorflight-firmware/blob/master/src/main/common/filter.c#L118
there is
```c
void biquadFilterInit(biquadFilter_t *filter, float filterFreq, uint32_t refreshRate, float Q, biquadFilterType_e filterType)
{
    ...
    const float alpha = sn / (2.0f * Q);
```
The 4th parameter `Q` is set to 0, I wonder how is that possible that MCU do not crash here with division by 0 exception? ;)
According to this article https://hackaday.com/2018/11/21/creating-black-holes-division-by-zero-in-practice/ division by 0 is allowed in floating point operations, but result in NaN. Technically `alpha` is not used in bessel variant, but you never know when it might kick us :)
Personally I'd use `1.0` here, just for sure. If you want, I can prepare PR.

**Comment by rotorflight** [comment]
Indeed it will result a NaN, but alpha is not used with the Bessel variant, so that's fine.
There are places elsewhere with similar slack programming, so I would not worry about that too much.
Also, this code has already disappeared in a later version.
