### ISSUE TITLE
SBUS Out

### ISSUE THREAD

**Issue by robthomson** [rotorflight/rotorflight-firmware#165]
Enable 'SBUS OUT' for 0-8ch' via any spare uart.

This is being handled by Bob00

**Comment by gongtao0607** [comment]
> Aim is to be able to assign a uart as an sbus out port.
> Two modes of operation.
>  *   Simple passthrough of all rx channels and send out via the sbus
>  *   Channel 1-8 using the values from after the mixer..  9-16 as passthrough
> 
> Primary and key mode would be option 2
> Essentially this will open the door to using sbus servos and of course for scale models where more servos are required
