### ISSUE TITLE
Rescue mode rate limiting


### ISSUE THREAD

**Issue by pkaig** [rotorflight/rotorflight-firmware#6]
One improvement to the rescue mode would be rate of change limiting (negative direction) on return from rescue mode...... The issue is if you rescue from inverted and it rolls to upright --- if you don't raise the collective stick before you exit rescue mode it will immediately pitch down negative to match your collective stick position (can be really rapid). It would be good to rate limit the reduction in collective until the collective command >= rate limit. I'm thinking this would be more of an issue if/when auto rescue based on baro was implemented.

**Comment by rotorflight** [comment]
Moved to rotorflight repo, as this affects the whole system, not only the firmware
