### ISSUE TITLE
Logging: mass storage device mode limits number of log files to 100

### ISSUE THREAD

**Issue by egonl** [rotorflight/rotorflight-firmware#68]
When more than 100 files are stored on flash memory, only the first 100 can be accessed when you activate *Mass Storage Device Mode*. I think it has to do with EMFAT_MAX_LOG_ENTRY, which is also 100.

Work-around: you can access all files by clicking *Save to file* in the Configurator. This takes a while and results in one big file, where each individual log file is a part.

**Comment by rotorflight** [comment]
yes it is limited to 100. There seems to be issue going over 127, so 100 is a good number. IMHO it should be enough.
