### ISSUE TITLE
Serial Pin Swap feature available without CLI commands

### ISSUE THREAD

**Issue by rotorflight** [rotorflight/rotorflight-firmware#79]
Serial pin swap should be possible to do in the Configurator without CLI commands.

**Comment by rotorflight** [comment]
Exactly that!

**Comment by azaz44** [comment]
So happy to hear that! Having most important cable in the heli connected on normal servo connector with thicker wire will make me sleep better :)

**Comment by rotorflight** [comment]
DONE!!!!
