### ISSUE TITLE
Fix cell count does not affect configurator (potentially the internal calculation as well)

### ISSUE THREAD

**Issue by etocii** [rotorflight/rotorflight-firmware#97]
A low voltage 12s pack can still be recognized as 11s even if cell count is set to 12
<img width="665" alt="Screenshot_2024-03-27_at_1 01 57_PM" src="https://github.com/rotorflight/rotorflight-firmware/assets/124343158/da371705-ef71-4112-bf02-f23eedb7628d">

**Comment by rotorflight** [comment]
Fixed in 2.0.0-RC2
